services:
  mongo:
    image: mongo:latest
    build: ./mongodb_rs
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=AuthvJR24
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27017
    ports:
      - '27017:27017' 